#version 450

struct Particle
{
    vec2 position;
    vec2 velocity;
    vec4 colour;
};

layout(binding = 0) uniform ParticleUBO
{
    float delta_time;
} ubo;

layout(std140, binding = 1) readonly buffer ParticleSSBOIn
{
    Particle in_particles[];
};

layout(std140, binding = 2) buffer ParticleSSBOOut
{
    Particle out_particles[];
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;
    vec2 new_velocity = in_particles[index].velocity;
    vec2 new_position = in_particles[index].position;
    out_particles[index].position = new_position + (new_velocity * ubo.delta_time);
    out_particles[index].velocity = new_velocity;
    out_particles[index].colour = in_particles[index].colour;
}